import { Component, OnChanges, OnInit } from '@angular/core';

@Component({
  selector: 'app-input-btn-unit',
  template: `
    <input type="text" [value]="generateTitle()">
    <button> Save </button>
  `,
  styleUrls: ['./input-btn-unit.component.scss']
})
export class InputBtnUnitComponent implements OnInit {

  title = 'Hello World - From Property';
  constructor() {
  }

  ngOnInit(): void {
  }

  generateTitle(): string {
    return 'This title was generated by a method';
  }

}
